# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysqlCreateDatabase:
    container_name: myOwnDataBase
    build: ./mysql/    #Dockerfileからビルドすることを示す
    ports:
      - "8888:3306"
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d  #初期データをマウントする場所

    image: original_mysql_create_database # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=databasepassword   #コンテナ内のMySQLを起動する際のパスワードを設定
