
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: command
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npx prisma migrate dev --name init"
    environment:
      DATABASE_URL: mysql://root:rootpassword@command_text_to_image_db_1:3306/command
    depends_on:
      - mysql
